# Generated by Django 2.1.7 on 2019-03-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='ecity',
            new_name='eid',
        ),
    ]
